language: node_js
node_js: stable

env:
    - TRAVIS_TEST=1

git:
  submodules: false
  depth: 3

cache:
  directories:
  - node_modules

before_install:

install:
  - if [ ! $TRAVIS_TEST ]; then exit 1; fi
  - echo $ssh_private_key | base64 --decode > ~/.ssh/id_rsa
  - chmod 0600 ~/.ssh/id_rsa
  - echo $ssh_public_key | base64 --decode > ~/.ssh/id_rsa.pub
  - chmod 0644 ~/.ssh/id_rsa.pub
  - echo -e "Host git.coding.net\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  - git clone --depth=3 --branch=main git@github.com:AfirSraftGarrier/ACCBefuncool.git
  - cd ACCBefuncool
  - git submodule update --init --recursive --remote
  - git config --global user.name 'AfirSraftGarrier'
  - git config --global user.email 'AfirsraftGarrier@gmail.com'
  - git commit -am "Sub module commit for update."
  - git push
