language: node_js
node_js: "12.18.3"

git:
  submodules: false
  depth: 3

cache:
  directories:
    - ~/.npm
    - node_modules

branches:
  only:
    - main

before_install:
  - echo $ssh_private_key | base64 --decode > ~/.ssh/id_rsa
  - chmod 0600 ~/.ssh/id_rsa
  - echo $ssh_public_key | base64 --decode > ~/.ssh/id_rsa.pub
  - chmod 0644 ~/.ssh/id_rsa.pub
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

install:
  - git submodule update --init --recursive --remote
  - sed -i'' "s~ALGOLIA_ADMIN_API_KEY~${algolia_admin_api_key}~" _config.yml
  - sed -i'' "s~ALGOLIA_ADMIN_API_KEY~${algolia_admin_api_key}~" themes/hexo-theme-acc/_config.yml
  - npm install -g hexo-cli
  - npm install
  - hexo clean
  - hexo algolia

before_script:
  - git config --global user.name 'AfirSraftGarrier'
  - git config --global user.email 'AfirsraftGarrier@gmail.com'

#script:
#  - hexo generate

after_success:
  - hexo deploy
