language: node_js
node_js: stable

git:
  submodules: false
  depth: 3

cache:
  directories:
  - ~/.npm
  - node_modules

before_install:
  - echo $ssh_private_key | base64 --decode > ~/.ssh/id_rsa
  - chmod 0600 ~/.ssh/id_rsa
  - echo $ssh_public_key | base64 --decode > ~/.ssh/id_rsa.pub
  - chmod 0644 ~/.ssh/id_rsa.pub
  - echo -e "Host git.coding.net\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

install:
  - rm -rf *
  - git clone --depth=3 --branch=main https://github.com/ACC-GIT/ACCBefuncool.git ACC-GIT/ACCBefuncool
  - git submodule update --init --recursive --remote
  - git config --global user.name 'AfirSraftGarrier'
  - git config --global user.email 'AfirsraftGarrier@gmail.com'
  - git commit -am "Sub module commit for update."
  - git push

before_script:

script:

after_success: