language: node_js
node_js: stable

git:
  submodules: false
  depth: 3

branches:
  only:
  - main

cache:
  directories:
  - ~/.npm
  - node_modules

before_install:
  - echo "success"

install:
  - echo "success"

before_script:
  - echo "success"

script:
  - echo "success"

after_success:
  - echo "success"