language: node_js
node_js: stable

cache:
  directories:
  -~/.nvm
  - ~/.npm
  - node_modules

before_install:


install:
#  - git submodule update --init --recursive --remote
  - sed -i 's/GIT_USER_NAME/2421078029@qq.com/' _config.yml
  - sed -i 's/GIT_PASSWORD/523114674/' _config.yml
  - sed -i 's/ALGOLIA_API_KEY/${algolia_api_key}/' _config.yml
  - sed -i 's/ALGOLIA_ADMIN_API_KEY/${algolia_admin_api_key}/' _config.yml
  - sed -i 's/ALGOLIA_API_KEY/${algolia_api_key}/' themes/hexo-theme-acc/_config.yml
  - sed -i 's/ALGOLIA_ADMIN_API_KEY/${algolia_admin_api_key}/' themes/hexo-theme-acc/_config.yml
  - npm install -g hexo-cli
  - npm install

before_script:
  - git config --global user.name 'AfirSraftGarrier'
  - git config --global user.email 'AfirSraftGarrier@gmail.com'

script:
  - hexo generate

after_success:
  - hexo deploy
