language: node_js
node_js: stable

cache:
  directories:
  - ~/.npm
  - node_modules

before_install:
  - echo $ssh_private_key | base64 --decode > ~/.ssh/id_rsa
  - chmod 0600 ~/.ssh/id_rsa
  - echo $ssh_public_key | base64 --decode > ~/.ssh/id_rsa.pub
  - chmod 0644 ~/.ssh/id_rsa.pub

install:
  #  - git submodule update --init --recursive --remote
  #  - sed -i 's/GIT_USER_NAME/${git_user_name}/' _config.yml
  #  - sed -i'' "s~GIT_USER_NAME~${git_user_name}~" _config.yml
  #  - sed -i'' "s~GIT_PASSWORD~${git_password}~" _config.yml
  - sed -i'' "s~ALGOLIA_ADMIN_API_KEY~${algolia_admin_api_key}~" _config.yml
  - sed -i'' "s~ALGOLIA_ADMIN_API_KEY~${algolia_admin_api_key}~" themes/hexo-theme-acc/_config.yml
  - npm install -g hexo-cli
  - npm install

before_script:
  - git config --global user.name 'AfirSraftGarrier'
  - git config --global user.email '2421078029@qq.com'

script:
  - hexo generate

after_success:
  - hexo deploy
