prose:
  rooturl: '_posts'
  siteurl: 'http://www.befuncool.com/'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "title"
          label: "标题"
          placeholder: "输入标题"
      - name: "date"
        field:
          element: "text"
          label: "时间"
          value: "2014-06-08 10:30:00"
      - name: "category"
        field:
          element: "select"
          label: "分类"
          placeholder: "文章分类"
          alterable: true
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
      - name: "tags"
        field:
          element: "multiselect"
          label: "标签"
          placeholder: "标签内容"
          alterable: true
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
      - name: "published"
        field:
          element: "checkbox"
          label: "发布"
          value: true