prose:
  rooturl: '_posts'
  metadata:
      - name: "date"
        field:
          element: "text"
          label: "Date (YYYY-MM-DD HH:MM:SS)"
          value: now
      - name: "category"
        field:
          element: "select"
          label: "分类"
          placeholder: "文章名字"
          alterable: true
      - name: "tags"
        field:
          element: "multiselect"
          label: "标签"
          alterable: true