prose:
  rooturl: '_posts'
  siteurl: 'http://www.befuncool.com/'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "标题"
          value: "这是标题"
      - name: "date"
        field:
          element: 'textarea'
          value: 'CURRENT_DATETIME'
          label: "时间"
      - name: "category"
        field:
          element: "multiselect"
          label: "分类"
          placeholder: "文章分类"
          alterable: true
          options:
            - name: "Android"
              value: "Android"
      - name: "tags"
        field:
          element: "multiselect"
          label: "标签"
          placeholder: "标签内容"
          alterable: true
          options:
            - name: "快捷键"
              value: "快捷键"
      - name: "published"
        field:
          element: "checkbox"
          label: "发布"
          value: true