prose:

  rooturl: '_posts'

  metadata:
    _posts:
      - name: "title"
        field:
          element: "title"
          value: "标题"
      - name: "date"
        field:
          element: "text"
          label: "时间"
          value: "2014-06-08 10:30:00"
      - name: "category"
        field:
          element: "select"
          label: "分类"
      - name: "tags"
        field:
          element: "multiselect"
          label: "标签"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "发布"
          value: true