prose:

  rooturl: '_posts'

  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          value: "标题在这里"
      - name: "date"
        field:
          element: "time"
          label: "时间 (YYYY-MM-DD HH:MM:SS)"
          value: "2014-06-08 10:30:00"
      - name: "category"
        field:
          element: "select"
          label: "分类"
          placeholder: "文章分类"
      - name: "tags"
        field:
          element: "multiselect"
          label: "标签"
          placeholder: "[标签一,标签二...]"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "是否发布"
          value: false