prose:
    metadata:
        _posts:
            - name: "title"
              field:
                element: "text"
                label: "标题"
                placeholder: "文章名字"
                alterable: true
            - name: "date"
                field:
                  element: "text"
                  label: "Date (YYYY-MM-DD HH:MM:SS)"
                  value: now
            - name: "category"
                field:
                  element: "select"
                  label: "分类"
                  placeholder: "文章名字"
                  alterable: true
            - name: "tags"
                field:
                  element: "multiselect"
                  label: "标签"
                  placeholder: "[标签一,标签二...]"
                  alterable: true
    ignore:
        - about
        - categories
        - common
        - images
        - one
        - tags
        - .travis.yml
        - _config.yml
        - bdunion.txt
        - CNAME
        - LICENSE
        - README.md
        - robots.txt